### ISSUE TITLE
Getting errors when running instarepl (worked fine on 0.8.0)

### ISSUE THREAD

**Issue by boxxxie** [LightTable/ClojureInstarepl#17]
```
java.lang.IllegalArgumentException: No method in multimethod 'handle' for dispatch value: editor.eval.clj.sonar
    at clojure.lang.MultiFn.getFn(MultiFn.java:156)
    at clojure.lang.MultiFn.invoke(MultiFn.java:229)
    at lighttable.nrepl.core$queued$fn__1398.invoke(core.clj:96)
    at clojure.core$comp$fn__4727.invoke(core.clj:2459)
    at clojure.tools.nrepl.middleware.interruptible_eval$run_next$fn__684.invoke(interruptible_eval.clj:159)
    at clojure.lang.AFn.run(AFn.java:22)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)
```

**Comment by kenny-evitt** [comment]
@boxxxie We're not officially supporting this plugin, or at least not for much longer. That said, can you run the same code in a tab for a Clojure file? Your code might be running an un-supported version of Clojure (pre 1.7.0). If you share your code, I'll take a quick look.

**Comment by kenny-evitt** [comment]
@boxxxie There might also be a problem with the upgrade. Would you add the info we request in the contributing guidelines?

**Comment by boxxxie** [comment]
I commented out all of my code. 
instarepl works when I open a new tab, but that is outside of my project. 
i tried with clojure 1.7 and 1.8
